image: python:3.7.3

pipelines:
  branches:
    development:
      - step:
          caches:
            - pip
            - pipenv
          script: # Modify the commands below to build your repository.
            - pipenv install --dev --deploy --system
            - tox test
            - pipe: atlassian/pypi-publish:0.2.7
              variables:
                PYPI_USERNAME: $PYPI_PRIVATE_USER
                PYPI_PASSWORD: $PYPI_PRIVATE_PASS
