image: python:3.7.3

pipelines:
  branches:
    master:
      - step:
          caches:
            - pip
          script:
            - pip install pipenv --upgrade
            - pipenv install --deploy
            - tox test
            - pipe: atlassian/pypi-publish:0.2.7
              variables:
                PYPI_USERNAME: $PYPI_PRIVATE_USER
                PYPI_PASSWORD: $PYPI_PRIVATE_PASS
